version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=/api/v1
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tombola
      - DB_USERNAME=tombola
      - DB_PASSWORD=secret
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        php artisan key:generate --force &&
        php artisan migrate:fresh --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: mysql:8.2
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tombola
      - MYSQL_USER=tombola
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=tombola
      - PMA_PASSWORD=secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: